services:
  - type: web
    name: help-api
    env: java
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/help-api.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: ${DATABASE_URL}
      - key: SPRING_DATASOURCE_USERNAME
        value: ${DATABASE_USERNAME}
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${DATABASE_PASSWORD}
